org: drkario
app: project-roomkey-scraper

service: get-latest-project-roomkey-data

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: python3.8
  timeout: 30
  region: us-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ssm:GetParameter
      Resource:
        - Fn::Join:
            - ":"
            - - arn:aws:ssm
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - parameter${self:custom.secretNames.googleCredentials}
        - Fn::Join:
            - ":"
            - - arn:aws:ssm
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - parameter${self:custom.secretNames.googleSheetId}
  environment:
    DAY_OFFSET: "1"
    TMP: /tmp
    TWITTER_API_KEY: ${ssm:/TWITTER_API_KEY~true}
    TWITTER_API_SECRET: ${ssm:/TWITTER_API_SECRET~true}
    TWITTER_ACCESS_TOKEN: ${ssm:/TWITTER_ACCESS_TOKEN~true}
    TWITTER_ACCESS_TOKEN_SECRET: ${ssm:/TWITTER_ACCESS_TOKEN_SECRET~true}
    GOOGLE_CREDENTIALS: ${self:custom.secretNames.googleCredentials}
    GOOGLE_SHEET_ID: ${self:custom.secretNames.googleSheetId}

package:
  include:
    - ./source
  exclude:
    - "*.csv"
    - "*.pdf"
    - "*.png"
    - "*.ipynb"
    - ".*ignore"
    - "package*.json"
    - node_modules/**
    - source/table_parser/**
    - tmp/**
    - venv/**
    - Dockerfile
    - docker-compose.yml

functions:
  cron:
    handler: handler.run
    events:
      - schedule: cron(0 3 ? * TUE-SAT *)
    layers:
      - { Ref: PythonRequirementsLambdaLayer }

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
  stage: ${opt:stage, self:provider.stage, "dev"}
  secretNames:
    googleCredentials: /PRT/${self:custom.stage}/Google/ServiceAccountCredentials
    googleSheetId: /PRT/${self:custom.stage}/Google/SheetId
