org: drkario
app: project-roomkey-scraper

service: get-latest-project-roomkey-data

provider:
  name: aws
  stage: ${opt:stage, "dev"}
  runtime: python3.8
  timeout: 30
  region: us-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - ssm:GetParameter
      Resource:
        - Fn::Join:
            - ":"
            - - arn:aws:ssm
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - parameter${self:custom.secretNames.twitterApiKey}
        - Fn::Join:
            - ":"
            - - arn:aws:ssm
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - parameter${self:custom.secretNames.twitterApiSecret}
        - Fn::Join:
            - ":"
            - - arn:aws:ssm
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - parameter${self:custom.secretNames.twitterAccessToken}
        - Fn::Join:
            - ":"
            - - arn:aws:ssm
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - parameter${self:custom.secretNames.twitterAccessTokenSecret}
        - Fn::Join:
            - ":"
            - - arn:aws:ssm
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - parameter${self:custom.secretNames.googleCredentials}
        - Fn::Join:
            - ":"
            - - arn:aws:ssm
              - Ref: AWS::Region
              - Ref: AWS::AccountId
              - parameter${self:custom.secretNames.googleSheetId}
  environment:
    DAY_OFFSET: "1"
    TMP: /tmp
    TWITTER_API_KEY: ${self:custom.secretNames.twitterApiKey}
    TWITTER_API_SECRET: ${self:custom.secretNames.twitterApiSecret}
    TWITTER_ACCESS_TOKEN: ${self:custom.secretNames.twitterAccessToken}
    TWITTER_ACCESS_TOKEN_SECRET: ${self:custom.secretNames.twitterAccessTokenSecret}
    GOOGLE_CREDENTIALS: ${self:custom.secretNames.googleCredentials}
    GOOGLE_SHEET_ID: ${self:custom.secretNames.googleSheetId}

package:
  include:
    - ./source
  exclude:
    - "*.csv"
    - "*.pdf"
    - "*.png"
    - "*.ipynb"
    - ".*ignore"
    - "package*.json"
    - node_modules/**
    - source/table_parser/**
    - tmp/**
    - venv/**
    - Dockerfile
    - docker-compose.yml

functions:
  cron:
    handler: handler.run
    events:
      - schedule: cron(0 3 ? * TUE-SAT *)
    layers:
      - { Ref: PythonRequirementsLambdaLayer }

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
  secretPath: /PRT/${opt:stage, self:provider.stage, "dev"}
  secretNames:
    twitterApiKey: ${self:custom.secretPath}/Twitter/ApiKey
    twitterApiSecret: ${self:custom.secretPath}/Twitter/ApiSecret
    twitterAccessToken: ${self:custom.secretPath}/Twitter/AccessToken
    twitterAccessTokenSecret: ${self:custom.secretPath}/Twitter/AccessTokenSecret
    googleCredentials: ${self:custom.secretPath}/Google/ServiceAccountCredentials
    googleSheetId: ${self:custom.secretPath}/Google/SheetId
