org: drkario
app: project-roomkey-scraper

service: get-latest-project-roomkey-data

provider:
    name: aws
    runtime: python3.8
    region: us-west-1
    environment:
        TWITTER_API_KEY: ${ssm:/TWITTER_API_KEY~true}
        TWITTER_API_SECRET: ${ssm:/TWITTER_API_SECRET~true}
        TWITTER_ACCESS_TOKEN: ${ssm:/TWITTER_ACCESS_TOKEN~true}
        TWITTER_ACCESS_TOKEN_SECRET: ${ssm:/TWITTER_ACCESS_TOKEN_SECRET~true}

package:
    include:
        - ./source
    exclude:
        - "*.csv"
        - "*.pdf"
        - "*.ipynb"
        - node_modules/**
        - source/table_parser/**
        - venv/**

functions:
    cron:
        handler: handler.run
        events:
            - schedule: cron(0 20 ? * MON-FRI *)

plugins:
    - serverless-python-requirements

custom:
    pythonRequirements:
        dockerizePip: non-linux
